In [1]:
import pandas as pd
import numpy as np

In [2]:
company=pd.read_csv('company_scraped.csv')

In [3]:
candidates = pd.read_csv('candidate_for_companies.csv')

In [12]:
candidates

,first_name,last_name,qualification_year,full_name,nhsei_regional_team,GMC_NB,first+last
0,Aabida,Adam,2016,Aabida Adam,North West Commissioning Region,7526872,Aabida Adam
1,Aabida,Merali,2013,Aabida Merali,South East Commissioning Region,7408812,Aabida Merali
2,Aachal,Patel,2011,Aachal Kiran Patel,London Commissioning Region,7149032,Aachal Patel
3,Aadil,Kothia,2017,Aadil Kothia,North West Commissioning Region,7561419,Aadil Kothia
4,Aadil,Patel,2015,Aadil Zabir Patel,North West Commissioning Region,7487593,Aadil Patel
...,...,...,...,...,...,...,...
58527,Zurqa,Rasul,2004,Zurqa Nafeesa Rasul,North West Commissioning Region,6101429,Zurqa Rasul
58528,Zuzana,Ahmad,2014,Zuzana Ahmad,London Commissioning Region,7501312,Zuzana Ahmad
58529,Zvi,Messing,1977,Zvi Ram Messing,North West Commissioning Region,2515748,Zvi Messing
58530,Zvi,Morris,1999,Zvi Saadia Joseph Morris,London Commissioning Region,4632878,Zvi Morris
58531,Zymrije,Beqiri,1984,Zymrije Beqiri,South East Commissioning Region,5171151,Zymrije Beqiri

In [5]:
company['profession_match']=company['profession'].str.contains('Doctor|Medical|Practitioner|gp|hospital|dentist|Physician',case=False)

In [6]:
company['business_match']=company['nature_of_business'].str.contains('Medical|hospital|health',case=False)

In [7]:
company['id']=company.index+1

In [8]:
company['Region']=company['Region'].apply(lambda x:str(x).title())

In [9]:
company

,name,qualification_year,borndate,profession,appointed_on,company_name,address,company_status,nature_of_business,first+last,Region,profession_match,business_match,id
0,Aadil Kothia,2017,1994,Company Director,16-Oct-14,SAFEWAY TRAVEL CENTRE LIMITED,"35 England Avenue, Blackburn, Lancashire, Engl...",Dissolved,NaN,Aadil Kothia,North West Commissioning Region,False,NaN,1
1,Aadil Kothia,2017,1994,General Practitioner,20-Jul-22,K1 HEALTH LTD,"6 Linnet Street, Preston, England, PR1 6TJ",Active,86210 - General medical practice activities,Aadil Kothia,North West Commissioning Region,True,True,2
2,Aadil Patel,2015,1991,Doctor,07-Oct-17,EAST LANCS SUPPLIERS LTD,"153 Buncer Lane, Blackburn, England, BB2 6SY",Active,46341 - Wholesale of fruit and vegetable juice...,Aadil Patel,North West Commissioning Region,True,False,3
3,Aadin Abdul Majid Hussein,2008,1985,Doctor,07-Jan-10,PRESCRIBE A DOCTOR LIMITED,"6 Monterey Court, Leicester, England, LE5 1AU",Active,85590 - Other education not elsewhere classified,Aadin Hussein,Midlands Commissioning Region,True,False,4
4,Aadin Hussein,2008,1985,Doctor,18-Nov-13,I AM UN LIMITED,"5 Monterey Court, Leicester, Leicestershire, E...",Active,68100 - Buying and selling of own real estate,Aadin Hussein,Midlands Commissioning Region,True,False,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43831,Zulqarnain Shah,2009,1985,Gp,16-Sep-14,SABIR MEDICAL SERVICES LIMITED,"C/O Marshall Peters Ltd Haskin Hall Farm, Wood...",Dissolved,86900 - Other human health activities,Zulqarnain Shah,North West Commissioning Region,True,True,43832
43832,Zulqarnain Shah,2009,1985,Director,22-Jan-18,SAFA JANNAT LIMITED,"Ams Medical Accountants, Floor 2, 9 Portland S...",Active,64209 - Activities of other holding companies ...,Zulqarnain Shah,North West Commissioning Region,False,False,43833
43833,Zunaira Ahmed,2016,1991,Doctor,27-Apr-23,DR ZA MEDICAL LTD,"71-75 Shelton Street, Covent Garden, London, U...",Active,86210 - General medical practice activities,Zunaira Ahmed,London Commissioning Region,True,True,43834
43834,Zunaira Javed,2006,1984,Doctor,21-Sep-21,ASHRAFS PROPERTIES LIMITED,"1 Popeley Grange, Liversedge, England, WF15 6AX",Active,68100 - Buying and selling of own real estate,Zunaira Javed,North East And Yorkshire Commissioning Region,True,False,43835
43835,Zunaira Yasmeen,1998,1976,Company Director,28-Jan-15,FIZZA MEDICS LTD,"Flannagans Accountants, 7 Bankside, The Waterm...",Active,86900 - Other human health activities,Zunaira Yasmeen,North East And Yorkshire Commissioning Region,False,True,43836

In [10]:
def func(row):
    result=np.nan
    priority=10
    flag= False
    for i in range(len(company['first+last'])):
        
        if row['first+last']==company['first+last'][i] and row['qualification_year']==company['qualification_year'][i]:
            flag= True
            if company['name'][i]!=row['first+last'] and company['name'][i]==row['full_name']:
            
                if row['nhsei_regional_team']==company['Region'][i]:

                    if company['profession_match'][i]==True:
                        return company['id'][i]
                                                          
                    elif company['business_match'][i]==True:
                        result= company['id'][i]
                        priority=1
                                                                    
                    elif priority>3:
                        priority=3
                        result= company['id'][i]  
                                                          
                elif priority>4:
                    result= company['id'][i]
                    priority=5 
            
            elif row['nhsei_regional_team']==company['Region'][i] and priority>2:

                if company['profession_match'][i]==True:
                    result= company['id'][i]
                    priority=2
                                                      
                elif company['business_match'][i]==True:
                    result= company['id'][i]
                    priority=4 
                                                                
                elif priority>6:
                    result= company['id'][i]
                    priority=6
        
        elif flag==True:
            break
    return result

In [ ]:
candidates['id']=candidates.apply(func,axis=1)

In [11]:
candidates.apply(func,axis=1)

KeyboardInterrupt: